import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#fbf9fd" },
  safeArea: { flex: 1 },
  content: { paddingBottom: 35 },

  modalBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(37, 29, 46, 0.36)",
    flex: 1,
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "82%",
    minHeight: "50%",
    padding: 20,
    width: "100%",
  },
  modalHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  modalTitle: {
    color: "#3b205f",
    fontSize: 18,
    fontWeight: "800",
  },
  countText: {
    color: "#8c7898",
    fontSize: 12,
    marginTop: 4,
  },
  closeButton: {
    alignItems: "center",
    backgroundColor: "#f7f0fa",
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  searchBox: {
    alignItems: "center",
    backgroundColor: "#f8f4f8",
    borderColor: "#eee7f1",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  listContent: {
    paddingBottom: 16,
  },
  provinceRow: {
    alignItems: "center",
    borderBottomColor: "#eee7f1",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 13,
  },
  provinceName: {
    color: "#5c4668",
    fontSize: 14,
    fontWeight: "600",
  },
  selectedRow: {
    backgroundColor: "#f7f0fa",
  },
  selectedName: {
    color: "#7142a5",
    fontWeight: "800",
  },
  emptyText: {
    color: "#8c7898",
    fontSize: 13,
    paddingVertical: 12,
    textAlign: "center",
  },
  amazonHeader: {
    backgroundColor: "#172b4d",
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  headerTop: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  shopHeader: { alignItems: "center", flexDirection: "row" },
  logo: {
    backgroundColor: "#f7c948",
    borderRadius: 9,
    height: 38,
    overflow: "hidden",
    width: 38,
  },
  logoImage: { height: "100%", width: "100%" },
  brand: { color: "#fff", fontSize: 19, fontWeight: "800", marginLeft: 9 },
  accountButton: {
    alignItems: "center",
    flexDirection: "row",
    gap: 5,
    marginLeft: "auto",
    marginRight: 15,
  },
  accountLabel: { color: "#fff", fontSize: 11, fontWeight: "700" },
  cartButton: {
    alignItems: "center",
    height: 38,
    justifyContent: "center",
    width: 34,
  },
  badge: {
    alignItems: "center",
    backgroundColor: "#f7c948",
    borderColor: "#172b4d",
    borderRadius: 8,
    borderWidth: 2,
    height: 18,
    justifyContent: "center",
    position: "absolute",
    right: -3,
    top: -2,
    width: 18,
  },
  badgeText: { color: "#172b4d", fontSize: 9, fontWeight: "800" },
  searchBar: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 12,
    flexDirection: "row",
    height: 46,
    marginTop: 12,
    overflow: "hidden",
  },
  searchInput: {
    color: "#172b4d",
    flex: 1,
    fontSize: 14,
    paddingHorizontal: 13,
    paddingVertical: 0,
  },
  searchClearButton: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  searchSuggestionList: {
    backgroundColor: "#fff",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    marginTop: 4,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  searchSuggestionItem: {
    alignItems: "center",
    borderBottomColor: "#eee7f1",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingVertical: 9,
  },
  searchSuggestionThumb: {
    alignItems: "center",
    backgroundColor: "#f7f2fa",
    borderRadius: 8,
    height: 34,
    justifyContent: "center",
    overflow: "hidden",
    width: 34,
  },
  searchSuggestionImage: {
    height: "100%",
    width: "100%",
  },
  searchSuggestionEmoji: { fontSize: 19 },
  searchSuggestionName: {
    color: "#5c4668",
    flex: 1,
    fontSize: 12,
    fontWeight: "700",
    marginLeft: 10,
  },
  searchButton: {
    alignItems: "center",
    backgroundColor: "#f7c948",
    height: "100%",
    justifyContent: "center",
    width: 48,
  },
  hero: {
    backgroundColor: "#dce8f5",
    borderRadius: 20,
    flexDirection: "row",
    marginHorizontal: 16,
    marginTop: 16,
    minHeight: 160,
    overflow: "hidden",
    padding: 18,
  },
  heroCopy: { flex: 1, zIndex: 1 },
  heroKicker: {
    color: "#c47735",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  heroTitle: {
    color: "#172b4d",
    fontSize: 28,
    fontWeight: "800",
    lineHeight: 34,
    marginTop: 8,
  },
  heroText: {
    color: "#53657c",
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
    maxWidth: 185,
  },
  heroButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#f7c948",
    borderRadius: 9,
    flexDirection: "row",
    gap: 7,
    marginTop: 13,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  heroButtonText: { color: "#172b4d", fontSize: 12, fontWeight: "800" },
  heroArt: { alignItems: "center", justifyContent: "center", width: 96 },
  heroSun: {
    backgroundColor: "#f7c948",
    borderRadius: 75,
    height: 118,
    opacity: 0.45,
    position: "absolute",
    width: 118,
  },
  lantern: { fontSize: 56, zIndex: 1 },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    paddingHorizontal: 16,
  },
  sectionTitle: { color: "#172b4d", fontSize: 18, fontWeight: "800" },
  seeAll: { color: "#c47735", fontSize: 12, fontWeight: "700" },
  categoryList: {
    gap: 16,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
  },
  category: { alignItems: "center", width: 68 },
  categoryActive: {
    borderBottomColor: "#f7c948",
    borderBottomWidth: 3,
    opacity: 0.8,
    paddingBottom: 4,
  },
  categoryIcon: {
    alignItems: "center",
    borderRadius: 20,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  categoryText: {
    color: "#53657c",
    fontSize: 11,
    marginTop: 8,
    textAlign: "center",
  },
  productGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 15,
  },
  productCard: { width: "48%" },
  shelfProductList: { gap: 12, paddingHorizontal: 16, paddingTop: 13 },
  shelfProductCard: { width: 153 },
  productImage: {
    alignItems: "center",
    borderRadius: 14,
    height: 155,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  shelfProductImage: { height: 135 },
  productImageObject: {
    borderRadius: 14,
    height: "100%",
    width: "100%",
  },
  productEmoji: { fontSize: 69 },
  heart: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.88)",
    borderRadius: 14,
    height: 29,
    justifyContent: "center",
    position: "absolute",
    right: 9,
    top: 9,
    width: 29,
  },
  productName: {
    color: "#172b4d",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 9,
  },
  price: { color: "#b55c26", fontSize: 15, fontWeight: "800", marginTop: 5 },
  delivery: { color: "#6b7c93", fontSize: 10, marginTop: 4 },
  promise: {
    alignItems: "center",
    backgroundColor: "#eef3f8",
    flexDirection: "row",
    marginHorizontal: 16,
    marginTop: 28,
    padding: 14,
  },
  promiseCopy: { flex: 1, marginLeft: 11 },
  promiseTitle: { color: "#54316d", fontSize: 13, fontWeight: "800" },
  promiseText: { color: "#917e9a", fontSize: 11, marginTop: 3 },
  noResults: {
    color: "#917e9a",
    fontSize: 14,
    paddingVertical: 24,
    textAlign: "center",
  },
  productModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "86%",
    minHeight: "50%",
    padding: 20,
    width: "100%",
    alignSelf: "stretch",
  },
  detailScrollContent: {
    paddingBottom: 16,
  },
  detailImage: {
    alignItems: "center",
    borderRadius: 18,
    height: 230,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  detailEmoji: { fontSize: 92 },
  detailClose: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.85)",
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    position: "absolute",
    right: 12,
    top: 12,
    width: 36,
  },
  detailHeader: { alignItems: "center", flexDirection: "row", marginTop: 18 },
  detailCopy: { flex: 1 },
  detailName: { color: "#3b205f", fontSize: 21, fontWeight: "800" },
  detailPrice: {
    color: "#7142a5",
    fontSize: 18,
    fontWeight: "800",
    marginTop: 7,
  },
  detailRating: {
    color: "#b55c26",
    fontSize: 12,
    fontWeight: "700",
    marginTop: 10,
  },
  detailFavorite: {
    alignItems: "center",
    backgroundColor: "#fff0f3",
    borderRadius: 20,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  detailDescription: {
    color: "#725c7f",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 14,
  },
  detailFacts: {
    borderTopColor: "#eee7f1",
    borderTopWidth: 1,
    marginTop: 16,
    paddingTop: 4,
  },
  detailFact: { flexDirection: "row", paddingVertical: 7 },
  detailFactLabel: { color: "#8c7898", fontSize: 12, width: 90 },
  detailFactValue: {
    color: "#5c4668",
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
  },
  detailTags: { color: "#7142a5", fontSize: 12, marginTop: 8 },
  detailServiceList: {
    borderTopColor: "#eee7f1",
    borderTopWidth: 1,
    marginTop: 14,
    paddingTop: 4,
  },
  serviceRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    paddingVertical: 8,
  },
  serviceCopy: { flex: 1, marginLeft: 10 },
  serviceTitle: { color: "#5c4668", fontSize: 12, fontWeight: "800" },
  serviceText: { color: "#8c7898", fontSize: 12, lineHeight: 17, marginTop: 2 },
  detailBenefits: {
    alignItems: "center",
    backgroundColor: "#f1eafa",
    borderRadius: 11,
    flexDirection: "row",
    marginTop: 16,
    padding: 12,
  },
  detailBenefitText: { color: "#654477", flex: 1, fontSize: 12, marginLeft: 9 },
  addButton: {
    alignItems: "center",
    backgroundColor: "#7142a5",
    borderRadius: 12,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 20,
    paddingVertical: 14,
  },
  addButtonText: { color: "#fff", fontSize: 14, fontWeight: "800" },
  cartModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "80%",
    minHeight: "45%",
    padding: 20,
  },
  checkoutModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "88%",
    minHeight: "50%",
    padding: 20,
    width: "100%",
  },
  emptyCart: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 46,
  },
  emptyCartTitle: {
    color: "#54316d",
    fontSize: 17,
    fontWeight: "800",
    marginTop: 12,
  },
  emptyCartText: {
    color: "#a18baa",
    fontSize: 13,
    marginTop: 7,
    textAlign: "center",
  },
  cartRow: {
    alignItems: "center",
    borderBottomColor: "#eee7f1",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingVertical: 12,
  },
  cartThumb: {
    alignItems: "center",
    borderRadius: 11,
    height: 52,
    justifyContent: "center",
    overflow: "hidden",
    width: 52,
  },
  cartEmoji: { fontSize: 27 },
  cartCopy: { flex: 1, marginHorizontal: 12 },
  cartName: { color: "#5c4668", fontSize: 14, fontWeight: "700" },
  cartPrice: {
    color: "#7142a5",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 5,
  },
  cartTotal: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  totalLabel: { color: "#725c7f", fontSize: 14 },
  totalPrice: { color: "#3b205f", fontSize: 18, fontWeight: "800" },
  checkoutButton: {
    alignItems: "center",
    backgroundColor: "#7142a5",
    borderRadius: 12,
    flexDirection: "row",
    gap: 9,
    justifyContent: "center",
    marginTop: 17,
    paddingVertical: 14,
  },
  checkoutSummaryCard: {
    backgroundColor: "#f8f4fa",
    borderRadius: 14,
    padding: 14,
  },
  checkoutSummaryRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
  },
  checkoutLabel: { color: "#8c7898", fontSize: 12 },
  checkoutValue: { color: "#54316d", fontSize: 12, fontWeight: "700" },
  checkoutAddressBox: {
    backgroundColor: "#fff",
    borderColor: "#eee7f1",
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 14,
    padding: 14,
  },
  checkoutSectionTitle: {
    color: "#3b205f",
    fontSize: 14,
    fontWeight: "800",
  },
  checkoutInput: {
    backgroundColor: "#f8f4fa",
    borderColor: "#eee7f1",
    borderRadius: 12,
    color: "#54316d",
    marginTop: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  checkoutMethodRow: {
    alignItems: "center",
    borderBottomColor: "#eee7f1",
    borderBottomWidth: 1,
    flexDirection: "row",
    paddingVertical: 12,
  },
  checkoutMethodText: {
    color: "#5c4668",
    fontSize: 13,
    fontWeight: "700",
    marginLeft: 10,
  },
  checkoutTotalBox: {
    backgroundColor: "#fffaf1",
    borderRadius: 14,
    marginTop: 14,
    padding: 14,
  },
  checkoutConfirmButton: {
    alignItems: "center",
    backgroundColor: "#7142a5",
    borderRadius: 12,
    flexDirection: "row",
    gap: 9,
    justifyContent: "center",
    marginTop: 16,
    paddingVertical: 14,
  },
  customerScreen: { backgroundColor: "#fbf9fd", flex: 1 },
  customerContent: { paddingBottom: 35, paddingHorizontal: 20, paddingTop: 28 },
  pageKicker: {
    color: "#7142a5",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1.4,
  },
  pageTitle: { color: "#3b205f", fontSize: 30, lineHeight: 36, marginTop: 7 },
  pageDescription: {
    color: "#8c7898",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 9,
    maxWidth: 300,
  },
  filterRow: { flexDirection: "row", gap: 10, marginTop: 24 },
  filterButton: {
    alignItems: "center",
    backgroundColor: "#f1eafa",
    borderRadius: 11,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  filterText: { color: "#7142a5", fontSize: 12, fontWeight: "700" },
  sortButton: {
    alignItems: "center",
    borderColor: "#eadff0",
    borderRadius: 11,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 13,
  },
  sortText: { color: "#725c7f", fontSize: 12 },
  exploreGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 14,
    marginTop: 22,
  },
  exploreCard: { width: "47%" },
  exploreImage: {
    alignItems: "center",
    borderRadius: 16,
    height: 155,
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  exploreEmoji: { fontSize: 62 },
  exploreHeart: {
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.84)",
    borderRadius: 14,
    height: 28,
    justifyContent: "center",
    position: "absolute",
    right: 9,
    top: 9,
    width: 28,
  },
  exploreName: {
    color: "#4f3a5e",
    fontSize: 13,
    fontWeight: "600",
    marginTop: 9,
  },
  explorePrice: {
    color: "#7142a5",
    fontSize: 14,
    fontWeight: "800",
    marginTop: 5,
  },
  subsectionTitle: {
    color: "#3b205f",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 13,
    marginTop: 30,
  },
  categoryRow: {
    alignItems: "center",
    borderBottomColor: "#eee7f1",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 62,
  },
  smallCategoryIcon: {
    alignItems: "center",
    borderRadius: 12,
    height: 39,
    justifyContent: "center",
    width: 39,
  },
  categoryRowText: {
    color: "#5c4668",
    flex: 1,
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 12,
  },
  accountCard: {
    alignItems: "center",
    backgroundColor: "#f1eafa",
    borderRadius: 17,
    flexDirection: "row",
    marginTop: 25,
    padding: 15,
  },
  accountProfileCard: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#eee7f1",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: 18,
    padding: 15,
  },
  accountAvatar: {
    alignItems: "center",
    backgroundColor: "#f1eafa",
    borderRadius: 25,
    height: 50,
    justifyContent: "center",
    width: 50,
  },
  accountCopy: { flex: 1, marginLeft: 12 },
  accountTitle: { color: "#54316d", fontSize: 15, fontWeight: "800" },
  accountText: { color: "#917e9a", fontSize: 11, marginTop: 4 },
  accountMetaRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 6,
    marginTop: 8,
  },
  accountMetaText: {
    color: "#7142a5",
    fontSize: 11,
    fontWeight: "700",
  },
  accountArrowButton: {
    alignItems: "center",
    backgroundColor: "#f7f0fa",
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  accountMetricsGrid: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  accountMetricCard: {
    alignItems: "center",
    backgroundColor: "#fff",
    borderColor: "#eee7f1",
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 14,
  },
  accountMetricValue: {
    color: "#3b205f",
    fontSize: 16,
    fontWeight: "800",
  },
  accountMetricLabel: {
    color: "#8c7898",
    fontSize: 11,
    marginTop: 4,
  },
  accountRow: {
    alignItems: "center",
    borderBottomColor: "#eee7f1",
    borderBottomWidth: 1,
    flexDirection: "row",
    minHeight: 72,
  },
  accountIcon: {
    alignItems: "center",
    backgroundColor: "#f1eafa",
    borderRadius: 12,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  accountRowCopy: { flex: 1, marginLeft: 12 },
  accountRowTitle: { color: "#5c4668", fontSize: 14, fontWeight: "700" },
  accountRowText: { color: "#a18baa", fontSize: 11, marginTop: 4 },
  accountRowBadge: {
    alignItems: "center",
    backgroundColor: "#fff4d9",
    borderRadius: 10,
    justifyContent: "center",
    marginRight: 10,
    minWidth: 30,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  accountRowBadgeText: {
    color: "#b55c26",
    fontSize: 11,
    fontWeight: "800",
  },
  helpCard: {
    alignItems: "center",
    backgroundColor: "#fff4d9",
    borderRadius: 15,
    flexDirection: "row",
    marginTop: 16,
    padding: 15,
  },
  accountPrimaryButton: {
    alignItems: "center",
    backgroundColor: "#7142a5",
    borderRadius: 12,
    flexDirection: "row",
    gap: 8,
    justifyContent: "center",
    marginTop: 26,
    paddingVertical: 13,
  },
  accountPrimaryButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "800",
  },
});
